### ISSUE TITLE
stacktrace on stop command

### ISSUE THREAD

**Issue by ssanden** [Nickduino/Pi-Somfy#59]
hi!

when i issue a stop command like
`/home/pi/Pi-Somfy/operateShutters.py b2 -c /home/pi/Pi-Somfy/operateShutters.conf -s`

i get the following stacktrace:
```
Traceback (most recent call last):
  File "/home/pi/Pi-Somfy/operateShutters.py", line 533, in <module>
    MyShutter = operateShutters(args = args)
  File "/home/pi/Pi-Somfy/operateShutters.py", line 368, in __init__
    self.ProcessCommand(args);
  File "/home/pi/Pi-Somfy/operateShutters.py", line 427, in ProcessCommand
    self.shutter.stop(self.config.ShuttersByName[args.shutterName])
  File "/home/pi/Pi-Somfy/operateShutters.py", line 155, in stop
    secondsSinceLastCommand = int(round(time.monotonic() - state.lastCommandTime))
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```
the command still gets executed, though.

great project, btw. - thanks a lot for this!
best regards

**Comment by MichaelB2018** [comment]
Thanks for raising. I fixed it an checked in a code change.
